# Generated by Django 3.2.8 on 2022-01-20 11:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_customuser_managers'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Group_Member',
            new_name='GroupMember',
        ),
    ]
