# Generated by Django 3.2.8 on 2021-12-01 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group_member',
            name='message',
            field=models.TextField(default='', help_text='Required'),
        ),
    ]
