# Generated by Django 3.2.8 on 2021-10-16 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='approved',
            field=models.CharField(choices=[(0, 'No'), (1, 'Yes')], default=False, max_length=25),
        ),
        migrations.AlterField(
            model_name='booking',
            name='username',
            field=models.CharField(max_length=30),
        ),
    ]
