# Generated by Django 3.2.8 on 2021-10-16 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0003_alter_booking_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='approved',
            field=models.CharField(choices=[(0, 'No'), (1, 'Yes')], default='No', max_length=25),
        ),
    ]
