# Generated by Django 3.2.8 on 2021-10-16 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0005_alter_booking_approved'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='instructor_requested',
            field=models.CharField(choices=[('No', 'No'), ('Yes', 'Yes')], max_length=5),
        ),
    ]
