# Generated by Django 3.2.8 on 2021-10-16 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0007_auto_20211016_2106'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='approved',
            field=models.IntegerField(choices=[('No', 0), ('Yes', 1)], default=False),
        ),
        migrations.AlterField(
            model_name='booking',
            name='instructor_requested',
            field=models.CharField(choices=[('No', 0), ('Yes', 1)], default=False, max_length=5),
        ),
    ]
