# Generated by Django 3.2.8 on 2021-10-16 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0009_auto_20211016_2114'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='instructor_requested',
            field=models.IntegerField(choices=[(0, 'No'), (1, 'Yes')], default=False),
        ),
    ]
