# Generated by Django 3.2.8 on 2021-10-17 18:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0010_alter_booking_instructor_requested'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='booking',
            options={'ordering': ['date', 'slot']},
        ),
    ]
