# Generated by Django 3.2.8 on 2021-10-17 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0011_alter_booking_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='slot',
            field=models.CharField(choices=[('0800-1000', '0800-1000'), ('1000-1200', '1000-1200'), ('1200-1400', '1200-1400'), ('1400-1600', '1400-1600'), ('1600-1800', '1600-1800')], max_length=11),
        ),
        migrations.DeleteModel(
            name='Slot',
        ),
    ]
