# Generated by Django 3.2.8 on 2021-10-21 08:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('booking', '0012_auto_20211017_1831'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='update_on',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='booking',
            name='slot',
            field=models.CharField(choices=[('0800-1000', '0800-1000'), ('1000-1200', '1000-1200'), ('1200-1400', '1200-1400'), ('1400-1600', '1400-1600'), ('1600-1800', '1600-1800')], default=False, max_length=11),
        ),
        migrations.AlterField(
            model_name='booking',
            name='username',
            field=models.ForeignKey(limit_choices_to={'is_active': True}, on_delete=django.db.models.deletion.CASCADE, related_name='tfs_users', to=settings.AUTH_USER_MODEL),
        ),
    ]
