# Generated by Django 3.2.8 on 2021-10-21 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0014_auto_20211021_1039'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slot',
            name='start',
            field=models.TimeField(auto_now=True),
        ),
    ]
