# Generated by Django 3.2.8 on 2021-10-24 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0020_alter_booking_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='username',
            field=models.CharField(max_length=30),
        ),
    ]
