# Generated by Django 3.2.8 on 2021-10-25 07:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0021_alter_booking_username'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='slot',
            options={'ordering': ['start']},
        ),
    ]
