# Generated by Django 3.2.8 on 2021-10-28 19:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0022_alter_slot_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='date',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='booking',
            name='instructor_requested',
            field=models.CharField(choices=[('No', 'No'), ('Yes', 'Yes')], default=False, max_length=5),
        ),
    ]
