# Generated by Django 3.2.8 on 2021-11-02 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0025_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='replied',
            field=models.IntegerField(choices=[(0, 'No'), (1, 'Yes')], default=False),
        ),
    ]
