# Generated by Django 3.2.8 on 2021-11-22 13:19

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0032_auto_20211122_1050'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='telephone',
            field=phonenumber_field.modelfields.PhoneNumberField(help_text='Include country code, eg +44', max_length=128, region=None),
        ),
    ]
