# Generated by Django 3.2.8 on 2021-11-23 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0034_auto_20211122_1647'),
    ]

    operations = [
        migrations.AddField(
            model_name='group_member',
            name='message',
            field=models.TextField(blank=True, help_text='Optional'),
        ),
    ]
