# Generated by Django 3.2.8 on 2021-11-23 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0035_group_member_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group_member',
            name='message',
            field=models.TextField(blank=True, help_text='Optional', null=True),
        ),
    ]
