# Generated by Django 3.2.8 on 2021-11-23 22:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('booking', '0036_alter_group_member_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group_member',
            name='message',
            field=models.TextField(blank=True, default='default message', help_text='Optional', null=True),
        ),
        migrations.AlterField(
            model_name='group_member',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='registered', to=settings.AUTH_USER_MODEL),
        ),
    ]
