# Generated by Django 3.2.8 on 2021-11-29 11:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('booking', '0037_auto_20211123_2220'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group_member',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='registered', to=settings.AUTH_USER_MODEL),
        ),
    ]
