# Generated by Django 3.2.8 on 2021-11-29 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0038_alter_group_member_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group_member',
            name='message',
            field=models.TextField(blank=True, help_text='Optional, but it would help us with your request!', null=True),
        ),
    ]
